const C = {
    ADD_RECIPE: "ADD_RECIPE",
    REMOVE_RECIPE: "REMOVE_RECIPE",
    ADD_PRODUCT: "ADD_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    UPDATE_RECIPE: "UPDATE_RECIPE",
}

export default C;