const C = {
    ADD_RECIPE: "ADD_RECIPE",
    REMOVE_RECIPE: "REMOVE_RECIPE",
    ADD_PRODUCT: "ADD_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    UPDATE_RECIPE: "UPDATE_RECIPE",
    ADD_MEAL: "ADD_MEAL",
    REMOVE_MEAL: "REMOVE_MEAL",
    ADD_SHOPPING_DAY: "ADD_SHOPPING_DAY",
    REMOVE_SHOPPING_DAY: "REMOVE_SHOPPING_DAY",
    GENERATE_SHOPPING: "GENERATE_SHOPPING",
    ADD_SHOPPING_ITEM: "ADD_SHOPPING_ITEM",
    REMOVE_SHOPPING_ITEM: "REMOVE_SHOPPING_ITEM"
}

export default C;